### ISSUE TITLE
is there any statistical concern on removing the gaussian probability from timepoint model

### ISSUE THREAD

**Issue by MacOSIcons** [freesurfer/samseg#1]
hello dr cerri, first of all, thank you for your great work in samseg. i noticed you are removing the gaussian probability from timepoint model in the longitudinal fitmodel. is there any specific statistical concern.

**Comment by ste93ste** [comment]
Closing, as your PR #2 add this flag. Thanks for that!

Note that this repository is still "under construction", so please use the [main repository](https://github.com/freesurfer/freesurfer) in the meantime.
