### ISSUE TITLE
how to use the mesh created by samseg? 

### ISSUE THREAD

**Issue by ZauberZ** [freesurfer/samseg#4]
I put --save-mesh at samseg command, and finally samseg created a mesh file. but it can not be used in freeview as rh.pial (recon-all). So,  how to use the mesh files created by samseg?

**Comment by ste93ste** [comment]
If you want to visualize the mesh with Freeview, there is a command in FreeSurfer to convert a samseg mesh to a FreeSurfer surface:
`samsegmesh2surf -h`
Note that we mostly save meshes for debugging or developing purposes. We do not fully support this feature at the moment.
