### ISSUE TITLE
Optimsing SAMSEG 

### ISSUE THREAD

**Issue by Adrija03** [freesurfer/samseg#5]
Hello! 
I am a masters student trying to optmise SAMSEG to detect WMH in stroke. I was wondering if it would be possible to add stroke images (with manually segmented WMH) to optimise the hyperparameters for modelling spatial location and shape of lesions. If so, I am struggling to find how to adapt the code to add images from or dataset for optimisation proposes, as I am new to coding. 
Kind regards, 
Adrija.

**Comment by ste93ste** [comment]
A couple of months ago I pushed some code that might be of interest to you in this [branch](https://github.com/freesurfer/samseg/tree/nf-new-samseg-lesion). There are scripts for training a shape model (VAE), as well as some intensity/location constraints. It's still WIP but might be pushed into the main repository in the next few months.

If you need more details, you can shoot me an email at scerri at mgh dot harvard dot edu.

Closing as it is not really an issue.
