### ISSUE TITLE
Does Samseg use the GPU?

### ISSUE THREAD

**Issue by lukaspirpamer** [freesurfer/samseg#9]
Dear Developers,

without cuda drivers, samseg issues a warning at the beginning that the GPU will not be used. This warning disappears after the cuda drivers are installed but the execution time was the same as before and "watch nvidia-smi" does not show any GPU usage at all.
Does the current version use the GPU at all? If not, do you have a GPU compiled version available or could you provide a short guide how to compile samseg with GPU support?

Thanks a lot!

Kind regards,
Lukas

**Comment by ste93ste** [comment]
Hi Lukas,

Only the lesion version of SAMSEG can be speed-up with a GPU (although very marginally). By default, samseg installed the CPU version of TensorFlow. If you want to use the GPU version, you would need to 1) uninstall the current version of TensorFlow and 2) install the GPU version of Tensorflow. As said before, the improvement would be marginal, as we have not optimized samseg yet to run fully on GPU. 

Stefano

**Comment by lukaspirpamer** [comment]
Hi Stefano,

thanks for the prompt reply!  In fact, I was using the lesion-segmentation workflow. Thanks a lot for the hint, I am going to try it out. 

Best,
Lukas
